version: "2.24.6"

services:
  django:
    build: .
    volumes:
      - .:/docker
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: compose
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata: null


